name: Release framework

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish_midil_kit:
    name: Publish Midil Kit
    runs-on: ubuntu-latest
    environment: "release"  # MUST match what you configured on Test PyPI
    # Only run for GA releases (no dev/beta/rc tags)
    # if: |
    #   startsWith(github.ref, 'refs/tags/v') &&
    #   !contains(github.ref_name, 'dev') &&
    #   !contains(github.ref_name, 'alpha') &&
    #   !contains(github.ref_name, 'beta') &&
    #   !contains(github.ref_name, 'rc')
    permissions:
      id-token: write  # Required for Trusted Publishing

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies and build
        run: |
          make install/ci
          make build

      - name: Publish to PyPI via Trusted Publishing
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ${{ github.workspace }}/dist
