name: Test Release to TestPyPI

on:
  push:
    tags:
      - v*-alpha*
      - v*-beta*
      - v*-rc*
      - v*-dev*
  workflow_dispatch:

env:
  TEST_PYPI_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
  TEST_PYPI_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}

jobs:
  test-publish:
    name: Test Publish to TestPyPI
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Make install and build
        run: |
            make install/ci
            make build
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ env.TEST_PYPI_USERNAME }}
          password: ${{ env.TEST_PYPI_PASSWORD }}
          packages-dir: ${{github.workspace}}/dist
          repository-url: https://test.pypi.org/legacy/

      - name: Remove 'v' from version name
        continue-on-error: true
        run: echo "VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//g')" >> $GITHUB_ENV
