name: Test Release to TestPyPI

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  id-token: write   # Required for Trusted Publishing
  contents: read    # Required to access the repo

jobs:
  test-publish:
    name: Test Publish to TestPyPI
    runs-on: ubuntu-latest
    environment: "test-release"  # MUST match what you configured on Test PyPI

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies and build
        run: |
          make install/ci
          make build

      - name: Publish to TestPyPI via Trusted Publishing
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: ${{github.workspace}}/dist
